[package]
name = "terminal_chat"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
crossterm = "0.27.0"
addr = "0.15.6"
terminal_size = "0.3.0"
